<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 6.2.1(579)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->integer('id')->unsigned()->autoIncrement();
            $table->string('choosenAvatar', 32)->nullable()->default(NULL);
            $table->string('defaultAvatar', 32)->nullable()->default(NULL);
            $table->string('firstName', 255);
            $table->string('lastName', 255);
            $table->string('sex', 255);
            $table->string('dob_month', 255);
            $table->string('dob_day', 255);
            $table->string('dob_year', 255);
            $table->string('email', 255);
            $table->bigInteger('goldBalance');
            $table->bigInteger('tokenBalance');
            $table->integer('citizenLevel');
            $table->timestamp('email_verified_at')->nullable()->default(NULL);
            $table->string('password', 255);
            $table->text('two_factor_secret')->nullable()->default(NULL);
            $table->text('two_factor_recovery_codes')->nullable()->default(NULL);
            $table->string('remember_token', 100)->nullable()->default(NULL);
            $table->timestamp('created_at')->nullable()->default(NULL);
            $table->timestamp('updated_at')->nullable()->default(NULL);
            $table->string('serverIP', 255)->default('127.0.0.1');
            $table->longtext('secondaryGroupIds')->nullable()->default('21');
            $table->integer('primaryGroupId')->default(5);
            $table->string('contentPath', 255)->default('https://content.yourdomain.com');
            $table->bigInteger('citizenPoints')->default(0);
            $table->string('security_question', 255)->nullable()->default(NULL);
            $table->string('security_answer', 255)->nullable()->default(NULL);
            $table->string('invite_code', 255)->nullable()->default(NULL);
            $table->double('deluxeSpinsRemaining')->nullable()->default(0);
            $table->timestamp('cooldownTimeRemaining')->nullable()->default(NULL);
        });
    }
   
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
