<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAvatarsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('avatars', function (Blueprint $table) {
            $table->integer('avatar_id')->unsigned()->autoIncrement();
            $table->foreign('avatar_id')->references('id')->on('users');
            $table->string('firstName');
            $table->string('lastName');
            $table->string('gender');
            $table->integer('nameInstance');
            $table->string('fullName');
            $table->boolean('takePet');
            $table->dateTime('dateCreated');
            $table->string('thumbUrl')->nullable();
            $table->string('snapUrl')->nullable();
            $table->longText('config');
            $table->string('headPostfix')->nullable();
            $table->string('snapshotPostfix')->nullable();
            $table->integer('homeSpaceId')->nullable();
            $table->integer('defaultAvatar');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('avatar_spaces');

        Schema::dropIfExists('avatars');
    }
}


// <?php

// use Illuminate\Support\Facades\Schema;
// use Illuminate\Database\Schema\Blueprint;
// use Illuminate\Database\Migrations\Migration;

// /**
//  * Migration auto-generated by TablePlus 6.2.1(579)
//  * @author https://tableplus.com
//  * @source https://github.com/TablePlus/tabledump
//  */
// class CreateAvatarsTable extends Migration
// {
//     /**
//      * Run the migrations.
//      *
//      * @return void
//      */
//     public function up()
//     {
//         Schema::create('avatars', function (Blueprint $table) {
//             $table->integer('id')->unsigned()->autoIncrement();
//             $table->string('cid', 255)->default('user.UserAvatar');
//             $table->string('avatar_id', 32);
//             $table->integer('owner_id')->unsigned();
//             $table->string('firstName', 255);
//             $table->string('lastName', 255);
//             $table->string('gender', 255);
//             $table->integer('nameInstance');
//             $table->string('fullName', 255);
//             $table->tinyInteger('takePet');
//             $table->datetime('dateCreated');
//             $table->string('thumbUrl', 255)->nullable()->default(NULL);
//             $table->string('snapUrl', 255)->nullable()->default(NULL);
//             $table->longtext('config');
//             $table->string('headPostfix', 255)->nullable()->default(NULL);
//             $table->string('snapshotPostfix', 255)->nullable()->default(NULL);
//             $table->integer('homeSpaceId')->nullable()->default(NULL);
//             $table->timestamp('created_at')->nullable()->default(NULL);
//             $table->timestamp('updated_at')->nullable()->default(NULL);
//             $table->string('selectedCPThemeKey', 255)->default('royal');
//             $table->string('overrideCPRankMinCL', 255)->nullable()->default(NULL);
//             $table->string('bonus', 255);
//         });
//     }
   
//     /**
//      * Reverse the migrations.
//      *
//      * @return void
//      */
//     public function down()
//     {
//         Schema::dropIfExists('avatar_spaces');
//         Schema::dropIfExists('avatars');
//     }
// }
